# Generated by Django 5.2.14 on 2026-05-20 04:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0002_order_estimated_time_order_updated_at_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='event',
            name='banner',
            field=models.URLField(max_length=1000),
        ),
        migrations.AlterField(
            model_name='event',
            name='image',
            field=models.URLField(max_length=1000),
        ),
        migrations.AlterField(
            model_name='event',
            name='lat',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='event',
            name='lng',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='menuitem',
            name='image',
            field=models.URLField(max_length=1000),
        ),
        migrations.AlterField(
            model_name='stall',
            name='banner',
            field=models.URLField(max_length=1000),
        ),
        migrations.AlterField(
            model_name='stall',
            name='image',
            field=models.URLField(max_length=1000),
        ),
        migrations.AlterField(
            model_name='user',
            name='avatar',
            field=models.URLField(blank=True, max_length=1000, null=True),
        ),
    ]
