# Generated by Django 5.2.14 on 2026-05-20 07:20

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("api", "0003_alter_event_banner_alter_event_image_alter_event_lat_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="order",
            name="payment_method",
            field=models.CharField(default="pay_at_stall", max_length=20),
        ),
    ]
